# Generated by Django 3.2 on 2021-04-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0002_alter_advice_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='photo_movie',
            field=models.FileField(blank=True, upload_to='driver_app/uploads'),
        ),
    ]
