# Generated by Django 3.2 on 2021-04-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_app', '0003_alter_advice_photo_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='users_passed_advice',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='driver_app.question'),
        ),
    ]
