# Generated by Django 3.2 on 2021-04-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0004_auto_20210427_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='question',
        ),
    ]
